apiVersion: v1
kind: Service
metadata:
  name: argodeploy-service
  namespace: argonsdemo
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
        #nodePort: 30007  # You can specify a port or let Kubernetes auto-assign one
  type: NodePort

